version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: airguy_role
      POSTGRES_PASSWORD: 123456

  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate & python3 manage.py runserver 0.0.0.0:8000"
