version: '3.3'
services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: django_rep2-backend
    restart: always
    volumes:
      - media_value:/app/media/
      - static_value:/app/staticfiles/
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ../star_burger/.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    container_name: django_rep2-frontend
    ports:
      - "3000:3000"

volumes:
  static_value:
  media_value:
  postgres_data:
