version: '3.3'
services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: django_rep2-backend
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ../star_burger/.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    container_name: django_rep2-frontend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
