# Generated by Django 4.1.5 on 2023-01-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличностью'), ('ELECTRONICALLY', 'Электронно')], default='ELECTRONICALLY', max_length=14, verbose_name='Способ оплаты'),
        ),
    ]
