# Generated by Django 4.1.3 on 2023-01-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_productinsomeorder_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='called',
            new_name='called_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivered',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='registered',
            new_name='registered_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличностью'), ('ELECTRONICALLY', 'Электронно')], max_length=14, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='productinsomeorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='productinsomeorder',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='кол-во продуктов'),
        ),
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.product', verbose_name='продукт'),
        ),
    ]
