# Generated by Django 4.1.5 on 2023-01-27 19:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_order_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productinsomeorder',
            managers=[
                ('product_type_cost', django.db.models.manager.Manager()),
            ],
        ),
    ]
