# Generated by Django 4.1.3 on 2023-02-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant_cooking_order',
            new_name='restaurant_cooking',
        ),
    ]
