# Generated by Django 4.1.3 on 2023-02-10 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_rename_restaurant_cooking_order_order_restaurant_cooking'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productinsomeorder',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='productinsomeorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена продукта'),
            preserve_default=False,
        ),
    ]
