# Generated by Django 4.1.7 on 2023-04-04 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_restaurant_latitude_restaurant_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinsomeorder',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='кол-во продуктов'),
        ),
    ]
